{
    'name': 'Vehicle Service Management',
    'version': '19.0.1.0.3',
    'category': 'Services/Workshop',
    'summary': 'Workshop Management: Vehicles, RO, Checklist, and Tabs',
    'author': 'Álvaro Jiménez Paz',
    'website': 'https://asinfo.cl',
    'license': 'AGPL-3',
    'depends': ['sale', 'sale_management', 'contacts', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'views/workshop_reports.xml',
        'views/sale_order_views.xml',
        'views/vehicle_views.xml',
        'views/report_reception_document.xml',
        'views/reception_email_template.xml',
        'views/sale_portal_templates.xml',
    ],
    'demo': [],
    'images': [],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
    'external_dependencies': {
        'python': [],
    },
}
